---

# An Ansible playbook to install a digital signage system on a Debian machine


- name: Signage user
  become: true
  hosts: all
  tasks:
    - name: Ensure svpb-signage user exists
      ansible.builtin.user:
        name: svpb-signage
        comment: "SVPB signage user"
        state: present
        shell: /bin/bash
        groups:
          - audio
          - dialout
          - render
          - video


- name: Basic software installation
  become: true
  hosts: all
  vars:
    - cloud_pkg_map:
        nextcloud: nextcloud-desktop-cmd
        owncloud: owncloud-client-cmd
  vars_files:
    - vars/cloud_vars.yml
  tasks:
    - name: Software needed for signage functionality
      ansible.builtin.apt:
        pkg:
          - cec-utils
          - chromium
          - lightdm-autologin-greeter
          - mpv
          - "{{ cloud_pkg_map[cloud_type] }}"
          - openbox
          - python3-xdg
          - unclutter
    - name: Utilities
      ansible.builtin.apt:
        pkg:
          - htop
          - intel-gpu-tools
          - lm-sensors
          - tmux
          - vim-nox


- name: Config files
  become: true
  hosts: all
  tasks:
    - name: Ensure openbox config directory exists
      ansible.builtin.file:
        dest: /home/svpb-signage/.config/openbox/
        state: directory
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure openbox config is placed
      ansible.builtin.copy:
        dest: /home/svpb-signage/.config/openbox/rc.xml
        src: files/openbox-rc.xml
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure openbox autostart config is placed
      ansible.builtin.copy:
        dest: /home/svpb-signage/.config/openbox/autostart
        src: files/openbox-autostart
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure lightdm config is placed
      ansible.builtin.copy:
        dest: /etc/lightdm/lightdm.conf.d/lightdm-autologin-greeter.conf
        src: files/lightdm-autologin-greeter.conf
    - name: Ensure mpv config directory exists
      ansible.builtin.file:
        dest: /home/svpb-signage/.config/mpv/
        state: directory
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure mpv config is placed
      ansible.builtin.copy:
        dest: /home/svpb-signage/.config/mpv/mpv.conf
        src: files/mpv.conf
        owner: svpb-signage
        group: svpb-signage


- name: Signage scripts
  become: true
  hosts: all
  vars_files:
    - vars/cloud_vars.yml
  tasks:
    - name: Ensure signage directory exists
      ansible.builtin.file:
        dest: /opt/svpb-signage/content/
        state: directory
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure user systemd directory exists
      ansible.builtin.file:
        dest: /home/svpb-signage/.config/systemd/user
        state: directory
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure systemd units are placed
      loop:
        - xsession.target
        - signage-cloud-sync.timer
        - signage-video.service
        - signage-video.timer
        - signage-video-loop.service
        - signage-video-loop-restart.path
        - signage-video-loop-restart.service
        - signage-website.service
      ansible.builtin.copy:
        dest: /home/svpb-signage/.config/systemd/user/{{ item }}
        src: files/{{ item }}
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure cloud synchronization service is placed
      ansible.builtin.template:
        dest: /home/svpb-signage/.config/systemd/user/signage-cloud-sync.service
        src: files/signage-cloud-sync.service
        owner: svpb-signage
        group: svpb-signage
    - name: Ensure cloud synchronization credential file is placed
      ansible.builtin.template:
        dest: /home/svpb-signage/.netrc
        src: files/dotnetrc
        owner: svpb-signage
        group: svpb-signage


- name: Systemd services and timer
  become: true
  hosts: all
  tasks:
    - name: Ensure TV on service is placed
      ansible.builtin.copy:
        dest: /etc/systemd/system/signage-tv-on.service
        src: files/signage-tv-on.service
        owner: root
        group: root
    - name: Ensure TV on service is enabled
      ansible.builtin.service:
        name: signage-tv-on.service
        enabled: true
    - name: Ensure TV standby service is placed
      ansible.builtin.copy:
        dest: /etc/systemd/system/signage-tv-standby.service
        src: files/signage-tv-standby.service
        owner: root
        group: root
    - name: Ensure TV standby service is enabled
      ansible.builtin.service:
        name: signage-tv-standby.service
        enabled: true
    - name: Ensure shutdown timer is placed
      ansible.builtin.copy:
        dest: /etc/systemd/system/signage-shutdown.timer
        src: files/signage-shutdown.timer
        owner: root
        group: root
    - name: Ensure shutdown timer is enabled
      ansible.builtin.service:
        name: signage-shutdown.timer
        enabled: true


- name: Configure screen rotation
  become: true
  hosts: all
  tasks:
    - name: Place grub config
      ansible.builtin.copy:
        dest: /etc/default/grub.d/grub-screen-rotation.cfg
        src: files/grub-screen-rotation.cfg
        owner: root
        group: root
      notify: Update grub
    - name: Place X11 config
      ansible.builtin.copy:
        dest: /etc/X11/xorg.conf.d/X-screen-rotation.conf
        src: files/X-screen-rotation.conf
        owner: root
        group: root

  handlers:
    - name: Update grub
      ansible.builtin.command:
        cmd: update-grub
